### ISSUE TITLE
Login Info

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-marketing#18]
@jeremywight has the FTP info changed for the marketing site? I can't login with the info in the PW file.

**Comment by jeremywight** [comment]
@agautsc no it should be the same. Want to connect on all the stuff
tonight or tomorrow? I don't have your number, 208-391-3140

**Comment by agautsc** [comment]
Do you have some time to talk tomorrow afternoon? 4pm.

**Comment by jeremywight** [comment]
Sure. I’m also coming to the keynote in the morning if you have time after.

**Comment by agautsc** [comment]
That works too.
