### ISSUE TITLE
Webform signup

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-marketing#20]
I went ahead and just put a Google form email signup for Beta Testers of both Android and iOS. That way we can send them a semi-personalized email and support any issues they might have. The form is made from the yeahthattrolley@gmail.com account. 

@jeremywight I'm not sure the hope difference in the two folders so one for TrackTheTrolley.com and one YeahThatTrolley.com so I might have messed up something in the secondary folder. I just copy and pasted the updated index.html page.

**Comment by jeremywight** [comment]
That's fine @agautsc That's all I did as well.
