### ISSUE TITLE
Outside signage

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-marketing#6]
- I asked Kathy from Greenlink about Greenlink signage. She said she planned on getting decals for the current signs to include a "Get the App" type call-to-action.
- I asked about a bigger sign for county square. I don't think I did a good enough job of explaining the concept to get a final answer. Probably worth putting together a quick mockup to at least best explain the idea.

**Comment by allella** [comment]
Closing this since decals and sign at County Square and the stadium are already done.

https://github.com/codeforgreenville/trolley-tracker/issues/151
