### ISSUE TITLE
Website code

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-marketing#7]
@jeremywight how much time and energy have you put into the WP marketing site? I only ask because we could use GitHub pages to create and host a simple site if our goal was to keep as much stuff on GitHub as possible. However, if you've put a bunch of time into the WP site it wouldn't make sense wipe all your efforts out and retrace steps.

**Comment by jeremywight** [comment]
I haven't put that much effort in, but other than the centralized file
structure is there any advantage to that? I'd prefer to keep it on a
standard host unless there is some advantage I'm not considering.

**Comment by jeremywight** [comment]
Also, I've got all the assets from Erwin Penland, just need to upload them once I'm on my personal computer.

**Comment by agautsc** [comment]
I'm not expert on either and don't have super strong opinions either way. Most of the articles about the pros and cons of GitHub Pages v WordPress speak of cost (free), speed, and no need to run things like security updates for GitHub pages. The pros for WP seem to be power that comes with additional plugins and some small server config things you can do. 
http://perfectionkills.com/moving-from-wordpress-to-github-pages/
http://www.sitepoint.com/blogging-wordpress-or-jekyll/

From hacking around on a new GH Pages site for CfG in general I will say there is a bit of learning curve for the straight up hacker / non-coder like me. But since this whole site might be nothing more than a page or three I wouldn't be that tough. 

At the end of the day, I'll let you make the choice, but if you want to do the GH pages thing I could probably put something together with a map and download links and the within an hour or two. Just let me know.

-Adam

**Comment by jeremywight** [comment]
I'm actually bit planning on using WP, just straight HTML. I installed WP
when someone else was going to work on it and never did. If I give you ftp
access toy could work on the page.

**Comment by jeremywight** [comment]
*you could work on the page.

**Comment by jeremywight** [comment]
Checkout the site: http://trackthetrolley.com/2/iframe-test.html

**Comment by agautsc** [comment]
Do you know if there is a way to have the map embedded without it zooming on scroll? It's a cool and useful thing to have map, but the page gets pretty unusable if you try to scroll down and instead of scrolling the the map zooms.

**Comment by dacohenii** [comment]
I think this might be possible by setting the `scrollWheelZoom` property (docs [here](http://leafletjs.com/reference.html#map-scrollwheelzoom)) inside the iframed window. I will see what I can find out.

**Comment by dacohenii** [comment]
confirmed that this method works and committed the changes: https://github.com/codeforgreenville/trolley-tracker-web/commit/7d5113044bb4b17fd4c31d8dea35fbae4d872700 

the changes won't be visible until deployed by @Linktheoriginal.

**Comment by jeremywight** [comment]
@dacohenii @Linktheoriginal Can we update the Web App to use the icons/colors provided by EP?

**Comment by Linktheoriginal** [comment]
Reviewing the changes and updating production... do we have defined colors anywhere?  I can't find them.

**Comment by jeremywight** [comment]
Style Guide with colors: https://app.box.com/s/6nm4aswmj4xzi9vao48kropxnocjw7bb

All Assets: https://app.box.com/s/mjrbf9d2vh8ixm264o21u0v6jhjue0tz

**Comment by Linktheoriginal** [comment]
Updated colors, waiting on data to verify before pushing to production.
