### ISSUE TITLE
Marketing Assets

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-marketing#8]
EP provided bunches of stuff to Jeremy today. Here's a big folder of such things 
https://drive.google.com/folderview?id=0B1Wxj_5D6dLNfnFEeXo3a3pFVl9VVmxmWWpaNElCaXJrUXhxNi0ycVdOb3Y2SzRrWExFRTA&usp=sharing

CC: @ajhodges @bikeoid @Linktheoriginal @austin9350

**Comment by ajhodges** [comment]
Nice!!!

**Comment by jeremywight** [comment]
Thanks @agautsc Everything should be there.

**Comment by agautsc** [comment]
All assets should be in the Google Drive doc https://drive.google.com/folderview?id=0B1Wxj_5D6dLNfnFEeXo3a3pFVl9VVmxmWWpaNElCaXJrUXhxNi0ycVdOb3Y2SzRrWExFRTA&usp=sharing

Closing issue.
